development:
  adapter: postgresql
  encoding: unicode
  database: hackprinceton_development
  pool: 5
  username: hackprinceton
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: hackprinceton_test
  pool: 5
  username: hackprinceton
  password: password1